.PHONY: clean All

All:
	@echo "----------Building project:[ Design_Patterns - Debug ]----------"
	@"$(MAKE)" -f  "Design_Patterns.mk"
clean:
	@echo "----------Cleaning project:[ Design_Patterns - Debug ]----------"
	@"$(MAKE)" -f  "Design_Patterns.mk" clean
