.PHONY: clean All

All:
	@echo "----------Building project:[ Design_Patterns - Debug ]----------"
	@"$(MAKE)" -f  "Design_Patterns.mk" /home/sainath-atmel/Documents/C_Patterns/Design_Patterns_states/State_Pattern_AtmStateWatch.h.gch && "$(MAKE)" -f  "Design_Patterns.mk"
clean:
	@echo "----------Cleaning project:[ Design_Patterns - Debug ]----------"
	@"$(MAKE)" -f  "Design_Patterns.mk" clean
