.PHONY: clean All

All:
	@echo "----------Building project:[ timer_wheel - Release ]----------"
	@cd "/home/sainath-atmel/Documents/C_Patterns/Timer_Wheel/timer_wheel" && "$(MAKE)" -f  "timer_wheel.mk"
clean:
	@echo "----------Cleaning project:[ timer_wheel - Release ]----------"
	@cd "/home/sainath-atmel/Documents/C_Patterns/Timer_Wheel/timer_wheel" && "$(MAKE)" -f  "timer_wheel.mk" clean
